name = "KiteSimulators"
uuid = "a262fb0b-5671-4fb4-9d61-972db9a18944"
authors = ["Uwe Fechner <fechner@aenarete.eu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
